apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api-deployment
  labels:
    app: pokemon-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pokemon-api
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
      - name: pokemon-api
        image: ghcr.io/schultyy/rust-pokemon-api:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-api-service
spec:
  selector:
    app: pokemon-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
